theme: jekyll-theme-minimal
<html>
<head>
<title>SHUYUNLI A1</title>
</head>
<body>
<h1>My IT Profile</h1> [My background]
<p>ShuyunLi(Julie)
Student id:s3845796
E-mail: s3845796@sdudent.rmit.edu.au
</p> This is an IT beginner which is who study the second year at RMIT, which means she still has a lot of things need to study in IT.
<h1>Interest in IT</h1>
<p>Since I was prepared for my College entrance examination I started interested in IT because my math teacher is a graduate of the IT program at university told me a lot. IT is No matter it has always been a high-paying profession, the more important fact is that the IT industry covers a wide range, including IT hardware equipment, software development, etc. At the same time, the IT industry is also being combined with a large number of traditional industries. In addition, the development of artificial intelligence, cloud computing, big data and other technologies in recent years has given IT The industry has brought new development opportunities. It can be said that the development space and development potential of the IT market are endless.
I chose RMIT because after a long term decision I heard from my agent that RMIT has a long term history and an excellent IT teaching environment, I find I need to study something new so I choose the RMIT IT program. Also, the city compass is nearby my apartment. I hope I can learn more python method through my RMIT study life.
</p>
</body>
</html>
